const str = `<p>中药</p>
<p>丹参;凉血，活血调经，消痈，安神，除烦<br>
红花活血&nbsp;炒麦芽回乳<br>
怀牛膝&nbsp;&nbsp;水&nbsp;活，补<br>
泽兰<br>
苏木<br>
血竭<br>
破血行气，消积止痛<br>
止咳平喘<br>
化痰<br>
蒲黄配五灵脂&nbsp;失笑散<br>
寒痰热痰<br>
半夏陈皮二陈汤<br>
消痞散结<br>
半夏&nbsp;脏腑之<br>
天南星&nbsp;经络之风痰<br>
白芥子&nbsp;温肺豁痰&nbsp;皮里膜外<br>
清热化痰<br>
川贝母<br>
浙贝母<br>
瓜蒌<br>
润肠通便&nbsp;宽胸散结<br>
薤白&nbsp;胸痹要药<br>
竹茹&nbsp;&nbsp;触犯<br>
淡竹叶不止<br>
天竺黄<br>
竹沥&nbsp;牛逼&nbsp;豁痰&nbsp;顽痰<br>
前胡&nbsp;白前&nbsp;车前子<br>
桔梗&nbsp;肺经&nbsp;宣肺祛痰&nbsp;寒热都治&nbsp;偏热痰&nbsp;利咽&nbsp;排脓&nbsp;肺佣&nbsp;参苓白术散<br>
海藻&nbsp;昆布<br>
海蛤壳<br>
苦杏仁，肺，大肠，止咳平喘，润肠通便<br>
紫苏子&nbsp;降气化痰+苦杏仁<br>
桃仁&nbsp;活血+苦杏仁&nbsp;&nbsp;<br>
百花紫<br>
枇杷叶&nbsp;<br>
宁心安神找志玲&nbsp;&nbsp;酸枣仁、远志、茯苓<br>
解郁安神&nbsp;合欢皮<br>
清心安神&nbsp;啥百合&nbsp;朱砂&nbsp;百合<br>
养心安神找莲柏&nbsp;莲子&nbsp;柏子仁<br>
潜阳安神&nbsp;磁石&nbsp;牡蛎&nbsp;<br>
震惊安神&nbsp;磁石&nbsp;龙骨&nbsp;珍珠母&nbsp;琥珀&nbsp;朱砂<br>
养血安神&nbsp;大乌龙&nbsp;<br>
龙骨收敛更强<br>
琥珀&nbsp;活血利尿</p>

<p>酸枣仁&nbsp;不敢学&nbsp;收敛&nbsp;汗生津&nbsp;宁&nbsp;<br>
柏子仁&nbsp;润肠通便&nbsp;连焊<br>
合欢皮&nbsp;活血&nbsp;解郁安神<br>
远志&nbsp;石菖蒲&nbsp;&nbsp;祛痰&nbsp;痰币<br>
首乌藤&nbsp;&nbsp;大枣&nbsp;龙眼肉<br>
带疼&nbsp;经络<br>
决明子、草决明&nbsp;&nbsp;通便，清肝明目<br>
石决明&nbsp;&nbsp;平肝潜阳&nbsp;凉肝&nbsp;镇肝<br>
珍珠母&nbsp;珍珠&nbsp;定惊安神，明目退翳&nbsp;<br>
珍珠母&nbsp;平肝潜阳安神<br>
珍珠&nbsp;解毒生肌，润肤祛斑</p>

<p>牡蛎&nbsp;&nbsp;软坚散结，制酸止痛<br>
龙骨&nbsp;镇静安神&nbsp;收湿敛疮<br>
潜阳安神，收敛固涩<br>
代赭石&nbsp;重镇降逆&nbsp;肝肺胃&nbsp;凉血止血<br>
刺蒺藜&nbsp;明目&nbsp;平肝疏肝&nbsp;活血祛风&nbsp;止痒<br>
罗布麻叶&nbsp;利水</p>

<p>息风止痉<br>
羚羊角&nbsp;偏肝&nbsp;清肝明目&nbsp;热极生风&nbsp;清热解毒<br>
牛黄&nbsp;偏心&nbsp;清心醒神&nbsp;开窍&nbsp;痰火闭<br>
心肝二经，凉肝熄风，清热解毒<br>
钩藤&nbsp;清热平肝，息风定惊&nbsp;后下<br>
天麻&nbsp;平抑肝阳&nbsp;眩晕、头痛无论虚实&nbsp;&nbsp;天麻钩藤饮<br>
僵蚕&nbsp;息风止痉&nbsp;祛风止痛&nbsp;化痰散结<br>
地龙&nbsp;通经络&nbsp;寒&nbsp;清热定惊&nbsp;平喘&nbsp;利尿<br>
全蝎&nbsp;<br>
蜈蚣&nbsp;更强<br>
通经络止痛&nbsp;以毒攻毒&nbsp;息风镇痉</p>

<p>开窍<br>
麝香&nbsp;开窍醒神要药&nbsp;消肿止痛&nbsp;活血通经&nbsp;闭证神昏&nbsp;0.1g<br>
冰片&nbsp;热闭<br>
苏合香&nbsp;寒闭&nbsp;辟秽<br>
石菖蒲&nbsp;痰闭&nbsp;化湿开胃&nbsp;噤口痢&nbsp;宁心安神</p>

<p>补虚<br>
补气<br>
人参&nbsp;&nbsp;安神益智<br>
党参&nbsp;&nbsp;小人参<br>
西洋参&nbsp;&nbsp;气阴双补&nbsp;清热<br>
太子参&nbsp;润肺<br>
补气生津<br>
黄芪&nbsp;肺脾之气&nbsp;补气升阳&nbsp;固表止汗&nbsp;利水消肿&nbsp;托疮生肌<br>
白术&nbsp;<br>
山药&nbsp;补肺脾肾之气&nbsp;补阴&nbsp;收she<br>
白扁豆&nbsp;解暑<br>
甘草&nbsp;肺脾心气&nbsp;草解毒</p>

<p>补阳<br>
鹿茸&nbsp;壮肾阳，益精血，强筋骨，调冲任，托疮毒&nbsp;1-2g&nbsp;一只鹿两只角<br>
紫河车&nbsp;温肾补精，养血益气<br>
&nbsp;&nbsp;拔羊毛组合&nbsp;<br>
&nbsp;仙茅&nbsp;冬天的茅房特别冷&nbsp;祛寒湿<br>
淫羊藿&nbsp;巴戟天&nbsp;&nbsp;祛风湿<br>
杜仲&nbsp;<br>
续断&nbsp;续折伤，止崩漏<br>
桑寄生&nbsp;祛风湿<br>
安胎&nbsp;补肝肾强筋骨<br>
肉苁蓉&nbsp;锁阳&nbsp;润肠通便<br>
补骨脂&nbsp;温脾止泻&nbsp;纳气平喘&nbsp;四神丸&nbsp;骨肉吴味&nbsp;<br>
沙苑子<br>
菟丝子&nbsp;补肾阴&nbsp;止泻安胎&nbsp;车前子&nbsp;止泻<br>
补肾阳、养肝明目、固精缩尿</p>

<p>
补血<br>
当归&nbsp;补血活血<br>
熟地黄&nbsp;<br>
生地黄&nbsp;清热凉血</p>

<p>固表止汗<br>
麻黄根<br>
浮小麦</p>

<p>敛肺涩肠<br>
五味子&nbsp;不要脸&nbsp;四神丸&nbsp;骨肉无畏&nbsp;五更泻&nbsp;补肾宁心&nbsp;天王补心丹<br>
五倍子&nbsp;倍要脸&nbsp;&nbsp;不补&nbsp;降火&nbsp;不止带<br>
诃子&nbsp;利咽<br>
乌梅&nbsp;生津&nbsp;安回虫<br>
肉豆蔻&nbsp;</p>

<p>
口诀：<br>
水火烫伤<br>
大地白虎紫冰石<br>
大黄&nbsp;地榆&nbsp;白及&nbsp;虎杖&nbsp;紫草&nbsp;冰片&nbsp;石膏&nbsp;要药地榆</p>

<p>杀虫<br>
川楝子&nbsp;百部&nbsp;苦参&nbsp;贯众&nbsp;萹蓄&nbsp;仙鹤草&nbsp;椿皮&nbsp;牵牛子&nbsp;芫花&nbsp;花椒&nbsp;砒石&nbsp;芦荟<br>
牵牛子&nbsp;去积杀虫</p>

<p>排脓<br>
介人白天穿二草+黄芪<br>
桔梗&nbsp;薏苡仁&nbsp;白芷&nbsp;天花粉&nbsp;穿山甲&nbsp;鱼腥草&nbsp;败酱草&nbsp;黄芪</p>

<p>凉血活血<br>
大四喜玉&nbsp;&nbsp;&nbsp;大小茜（止血+大黄）</p>

<p>透疹<br>
妈个紫金倍儿牛叉</p>

<p>泄水<br>
甘大芫&nbsp;</p>

<p>内风外风都治<br>
天上刮风三条虫<br>
天麻&nbsp;防风&nbsp;蕲蛇乌梢蛇&nbsp;僵蚕&nbsp;蝉蜕</p>

<p>祛风补肝肾强筋骨<br>
丧家狗<br>
桑寄生&nbsp;五加皮&nbsp;狗脊</p>

<p>补肝肾强筋骨安胎<br>
杜续生<br>
杜仲续断桑寄生</p>

<p>补火助阳<br>
附子肉桂耍流氓<br>
硫磺：通便</p>

<p>做题：<br>
青蒿&nbsp;清虚热，凉血除蒸，解暑，截疟<br>
芦根&nbsp;止呕<br>
紫草：预防麻疹<br>
青黛：定惊<br>
板蓝根：&nbsp;大头瘟<br>
佩兰：口臭<br>
滑石&nbsp;：清热解暑&nbsp;利尿通淋&nbsp;收湿敛疮<br>
木通：口疮<br>
丁香：呃逆<br>
吴茱萸：暖肝散寒<br>
小茴香：睾丸偏坠胀痛<br>
枳实：治各种下垂<br>
木香：行气止痛，气滞<br>
青皮：肝胆气滞<br>
沉香：纳气平喘<br>
香附：调经止痛&nbsp;气病之总司&nbsp;妇科之主帅<br>
车前子不解毒<br>
利胆退黄&nbsp;茵陈&nbsp;郁金<br>
回阳救逆&nbsp;附子&nbsp;干姜<br>
疏肝暖肝&nbsp;吴茱萸<br>
平阳疏肝&nbsp;刺蒺藜<br>
息风止痉&nbsp;清肝平阳&nbsp;钩藤<br>
清肝疏肝杀虫&nbsp;川楝子<br>
五倍子&nbsp;各种练<br>
五味子&nbsp;补要脸<br>
艾叶&nbsp;温经止血<br>
鸡内金&nbsp;小儿脾虚疳积<br>
槟榔&nbsp;杀虫&nbsp;截疟&nbsp;消积&nbsp;行气&nbsp;利水<br>
神曲：配金石、贝壳类助消化，发散风寒<br>
山楂：活血化瘀，化油腻要药<br>
谷芽能和中<br>
麦芽回乳消胀<br>
莱菔子&nbsp;降气化痰<br>
鸡内金&nbsp;涩精止遗&nbsp;化坚消石<br>
使君子&nbsp;杀虫消积<br>
茜草&nbsp;凉血止血活血&nbsp;通经、<br>
大蓟&nbsp;散瘀消痈<br>
小蓟&nbsp;治尿血<br>
艾叶&nbsp; 温经止血，散寒调经，安胎，崩漏<br>
蒲黄是花粉&nbsp;天花粉不是花粉<br>
白茅根&nbsp;清肺胃热&nbsp;清热利尿<br>
地榆&nbsp;治疗下焦出血&nbsp;解毒敛疮<br>
蒲黄茜草&nbsp;出血夹淤<br>
仙鹤草&nbsp;止痢<br>
牛膝&nbsp;利尿通淋&nbsp;引火（血）下行&nbsp;不消肿<br>
乳香没药&nbsp;消肿生肌<br>
延胡索&nbsp;专治一身上下诸痛，活血止痛<br>
血竭&nbsp;外用生肌敛疮&nbsp;内服化瘀止血<br>
鸡血藤&nbsp;行血补血&nbsp;月经不调&nbsp;风湿痹痛&nbsp;肢体瘫痪&nbsp;血虚经闭<br>
桃仁&nbsp;肺痈肠痈，止咳平喘<br>
姜黄&nbsp;活血行气，通经止痛风湿<br>
益母草&nbsp;利水消肿<br>
郁金&nbsp;利胆退黄&nbsp;清心凉血&nbsp;行气解郁<br>
川郁金&nbsp;活血化瘀&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;广郁金&nbsp;行气解郁<br>
川芎&nbsp;上行头目，下调经水，祛风止痛<br>
五灵脂&nbsp;胸腹血滞诸痛<br>
前胡&nbsp;祛痰解表<br>
紫菀&nbsp;化痰止咳要药&nbsp;配川贝母<br>
百部&nbsp;肺痨咳嗽要药<br>
白芥子&nbsp;寒痰壅肺，阴疽流注<br>
葶苈子桑白皮&nbsp;泻肺平喘&nbsp;利水消肿<br>
半夏&nbsp;燥湿化痰&nbsp;降逆止呕&nbsp;消痞散结<br>
天南星&nbsp;祛风止痉&nbsp;&nbsp;顽痰阻肺&nbsp;咳喘胸闷<br>
瓜蒌&nbsp;清热化痰&nbsp;宽胸散结&nbsp;润肠通便<br>
浙贝母&nbsp;散结消痈&nbsp;清热化痰<br>
川贝母&nbsp;润肺止咳&nbsp;散结消肿&nbsp;清热化痰<br>
枇杷叶&nbsp;清肺止咳&nbsp;降逆止呕<br>
桔梗&nbsp;宣肺&nbsp;祛痰&nbsp;利咽&nbsp;排脓<br>
旋覆花&nbsp;破血通经&nbsp;也降逆止呕<br>
苏子&nbsp;咳喘痰壅&nbsp;胸闷食积<br>
白附子&nbsp;祛风止痉&nbsp;止痛&nbsp;解毒散结</p>

<p>琥珀&nbsp;活血利尿<br>
朱砂&nbsp;善于口疮<br>
远志&nbsp;祛痰开窍&nbsp;宁心安神&nbsp;消痈散结<br>
石菖蒲&nbsp;化湿开窍&nbsp;宁心安神<br>
酸枣仁&nbsp;养心安神&nbsp;敛汗<br>
磁石&nbsp;聪耳明目&nbsp;纳气平喘&nbsp;平肝潜阳&nbsp;镇惊安神<br>
煅龙骨&nbsp;收敛固涩</p>

<p>地龙&nbsp;清热定惊&nbsp;通络&nbsp;平喘&nbsp;利尿&nbsp;关节疼痛<br>
天麻&nbsp;性平&nbsp;息风止痉&nbsp;平抑肝阳&nbsp;祛风通络，肝风内动要药&nbsp;寒热惊都治<br>
代赭石&nbsp;哮喘有声&nbsp;卧睡不得<br>
僵蚕&nbsp;疏散风热，头痛目赤，风疹瘙痒，口眼歪斜<br>
全蝎蜈蚣&nbsp;顽固头痛<br>
牛黄&nbsp;化痰开窍，清热解毒<br>
羚羊角&nbsp;热极生风<br>
鳖甲&nbsp;阴虚动风<br>
刺蒺藜&nbsp;平肝疏肝<br>
牡蛎&nbsp;胃酸<br>
罗布麻&nbsp;利尿<br>
山药&nbsp;脾虚泄泻&nbsp;肺虚咳喘补脾养胃，生津益肺，补肾涩精<br>
石斛&nbsp;养阴清热&nbsp;益胃生津<br>
白术&nbsp;健脾益气&nbsp;燥湿利尿&nbsp;止汗&nbsp;安胎&nbsp;生用燥湿利水&nbsp;炒用补气健脾益气&nbsp;炒焦健脾止泻<br>
蛤蚧&nbsp;补肺益肾&nbsp;纳气平喘&nbsp;助阳益精<br>
麦冬&nbsp;养阴润肺&nbsp;益胃生津<br>
黄芪&nbsp;补气升阳&nbsp;固表止汗&nbsp;利水消肿&nbsp;托疮生肌<br>
天冬&nbsp;养阴润燥&nbsp;清肺生津<br>
白芍&nbsp;养血敛阴&nbsp;柔肝止痛&nbsp;平抑肝阳&nbsp;四肢痉挛<br>
熟地黄&nbsp;补血养阴&nbsp;填精益髓&nbsp;补血要药<br>
墨旱莲&nbsp;养阴益肾&nbsp;凉血止血<br>
阿姣&nbsp;补血止血<br>
当归&nbsp;补血调经&nbsp;活血止痛&nbsp;润肠通便<br>
黄精&nbsp;补气养阴&nbsp;健脾&nbsp;润肺&nbsp;益肾<br>
玉竹&nbsp;养阴润燥&nbsp;生津止渴<br>
西洋参&nbsp;中阳衰微，胃有寒湿忌服<br>
鹿茸&nbsp;补肾阳，益精血，强筋骨，调冲任，托疮毒<br>
白扁豆&nbsp;脾胃气弱&nbsp;暑湿吐泻<br>
龟甲&nbsp;滋阴潜阳&nbsp;益肾健骨&nbsp;养血补心<br>
菟丝子&nbsp;补肾益精&nbsp;固精缩尿&nbsp;养肝明目&nbsp;止泻安胎<br>
人参&nbsp;大补元气&nbsp;补脾益肺&nbsp;生津&nbsp;安神益智<br>
枸杞子&nbsp;滋补肝肾&nbsp;益精明目<br>
益智仁&nbsp;暖肾固精缩尿&nbsp;问脾开胃摄唾<br>
冬虫夏草&nbsp;补肾益肺&nbsp;止血化痰<br>
何首乌&nbsp;生：解毒，截疟，润肠通便&nbsp;制：补益精血<br>
女贞子&nbsp;滋补肝肾，乌须明目<br>
大枣&nbsp;脏躁失眠<br>
覆盆子&nbsp;固精缩尿&nbsp;益肝肾明目<br>
乌梅&nbsp;敛肺止咳&nbsp;涩肠止泻&nbsp;安蛔止痛&nbsp;生津止渴<br>
五味子&nbsp;收敛固涩&nbsp;益气生津&nbsp;补肾宁心&nbsp;久虚咳喘<br>
椿皮&nbsp;清热燥湿&nbsp;涩肠止泻<br>
山茱萸&nbsp;补益肝肾&nbsp;收敛固涩&nbsp;平补阴阳<br>
金樱子&nbsp;固精缩尿止带&nbsp;涩肠止泻<br>
莲子&nbsp;固精止带&nbsp;补脾止泻&nbsp;益肾养心<br>
硫磺&nbsp;&nbsp;杀虫解毒&nbsp;燥湿止痒&nbsp;&nbsp;助阳通便&nbsp;疥癣湿疹&nbsp;虚喘冷哮&nbsp;内服与豆腐同煮<br>
土茯苓&nbsp;梅毒&nbsp;湿热疮毒<br>
蟾蜍&nbsp;解毒止痛&nbsp;开窍醒神<br>
苦楝皮&nbsp;杀虫&nbsp;疗癬<br>
贯众&nbsp;清热解毒&nbsp;止血崩漏&nbsp;杀虫<br>
槟榔&nbsp;不止血<br>
细辛&nbsp;发表散寒&nbsp;温肺化饮<br>
香薷&nbsp;夏季乘凉饮冷&nbsp;阳气被阴邪所遏之阴暑证<br>
升麻&nbsp;升阳解毒<br>
桂枝汤&nbsp;桂枝&nbsp;白芍&nbsp;汗出<br>
麻黄汤&nbsp;无汗，喘<br>
知母&nbsp;清热泻火&nbsp;滋阴润肺<br>
夏枯草&nbsp;痰火凝结&nbsp;瘿瘤瘰疬&nbsp;<br>
金银花&nbsp;清热解毒&nbsp;疏散风热&nbsp;凉血<br>
山豆根&nbsp;&nbsp;清热解毒&nbsp;利咽&nbsp;消肿<br>
牡丹皮&nbsp;凉血活血<br>
地骨皮&nbsp;凉血退蒸&nbsp;清泄肺热<br>
甘遂不宜入煎剂<br>
攻下&nbsp;食积<br>
润下&nbsp;便秘<br>
峻下逐水&nbsp;水肿<br>
秦艽&nbsp;风药中之润剂<br>
防己&nbsp;风湿热痹<br>
独活&nbsp;解表<br>
芳香化湿&nbsp;主治湿阻中焦<br>
藿香&nbsp;芳香化湿&nbsp;和中止呕&nbsp;解表祛暑<br>
薏苡仁&nbsp;健脾祛湿&nbsp;清热排脓&nbsp;利水消肿<br>
槐花&nbsp;凉血止血&nbsp;清肝泻火<br>
侧柏叶&nbsp;凉血止血&nbsp;化痰止咳&nbsp;生发乌发<br>
甘草过多会浮肿</p>`;
export default str;