/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanBarrage: typeof import('vant/es')['Barrage']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanSpace: typeof import('vant/es')['Space']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTag: typeof import('vant/es')['Tag']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
